#
# This playbook installs:
# - Geth (Eth1)
# - Lighthouse (Eth2)
# - Besu (Eth1)
# - Teku (Eth2)
# - Prometheus
# - Grafana

---
- name: Eth2 Validator Playbook (Mainnet and Pyrmont)
  hosts: all

  # By default this playbook uses the 'ubuntu' user, but this can be
  # overwritten with the PLAYBOOK_USER environment variable. This user needs
  # sudo access on the remote system.
  user: "{{ lookup('env', 'PLAYBOOK_USER') | default('ubuntu') }}"

  tasks:
    #
    # Misc Pre-Install Stuff
    #
    - import_tasks: tasks/pre-install.yml
    
    #- import_tasks: tasks/tight-umask.yml # conflicts with besu & teku

    #
    # Main Installation
    #
    - import_tasks: tasks/grub.yml

    - import_tasks: tasks/chrony.yml
    
    - import_tasks: tasks/unattented-upgrades.yml
    
    - import_tasks: tasks/sensors.yml
    
    - import_tasks: tasks/sata-mount.yml

    - import_tasks: tasks/usb-automount.yml

    #- import_tasks: tasks/ups.yml

    #
    # Clients Installation
    #
    - import_tasks: tasks/rust.yml

    - import_tasks: tasks/geth.yml
    
    - import_tasks: tasks/lighthouse.yml

    - import_tasks: tasks/metrics.yml

    - import_tasks: tasks/besu.yml

    - import_tasks: tasks/teku.yml

    #- import_tasks: tasks/scripts.yml
