---

- name: Besu - install java and unzip
  become: yes
  apt:
    pkg:
      - openjdk-11-jdk
      - unzip
    state: latest
    update_cache: yes

- name: Besu - create dedicated user
  become: yes
  user:
    name: besu
    create_home: no
    home: /nonexistent
    shell: /bin/false

- name: Besu - prepare workspace for user
  become: yes
  file:
    path: /var/lib/besu
    state: directory
    recurse: yes
    mode: o-rwx
    owner: besu
    group: besu

- name: Besu - download zip
  become: yes
  get_url:
    url: https://dl.bintray.com/hyperledger-org/besu-repo/besu-20.10.1.zip
    dest: /var/lib/besu/besu-20.10.1.zip
    checksum: sha256:ac4fae310957c176564396f73c0f03c60c41129d43d078560d0dab533a69fd2a
    owner: besu
    group: besu

- name: Besu - extract zip
  become: yes
  unarchive:
    src: /var/lib/besu/besu-20.10.1.zip
    dest: /var/lib/besu/
    remote_src: yes
    owner: besu
    group: besu
- name: Move foo to bar
  become: yes
  command: mv /var/lib/besu/besu-20.10.1 /var/lib/besu/besu-client

- name: Besu - install systemd service
  become: yes
  copy:
    src: files/systemd/besu.service
    dest: /etc/systemd/system/besu.service
    owner: root
    group: root
    mode: 0600

- name: systemd daemon-reload
  become: yes
  systemd:
    daemon_reload: yes

- name: UFW - allow port 30303 (Besu)
  become: yes
  ufw:
    rule: allow
    port: '30303'