---
- name: update APT packages
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: UFW - allow SSH
  become: yes
  ufw:
    rule: allow
    name: OpenSSH

- name: UFW - turn on
  become: yes
  ufw:
    state: enabled
...
